package com.wrbug.polymarketbot.dto

import java.math.BigDecimal
import java.time.LocalDate

/**
 * NBA 量化策略 DTO
 */
data class NbaQuantitativeStrategyDto(
    val id: Long?,
    val strategyName: String,
    val strategyDescription: String?,
    val accountId: Long,
    val accountName: String?,
    val enabled: Boolean,
    val filterTeams: List<String>?,
    val filterDateFrom: LocalDate?,
    val filterDateTo: LocalDate?,
    val filterGameImportance: String?,
    val minWinProbabilityDiff: BigDecimal,
    val minWinProbability: BigDecimal?,
    val maxWinProbability: BigDecimal?,
    val minTradeValue: BigDecimal,
    val minRemainingTime: Int?,
    val maxRemainingTime: Int?,
    val minScoreDiff: Int?,
    val maxScoreDiff: Int?,
    val buyAmountStrategy: String,
    val fixedBuyAmount: BigDecimal?,
    val buyRatio: BigDecimal?,
    val baseBuyAmount: BigDecimal?,
    val buyTiming: String,
    val delayBuySeconds: Int,
    val buyDirection: String,
    val enableSell: Boolean,
    val takeProfitThreshold: BigDecimal?,
    val stopLossThreshold: BigDecimal?,
    val probabilityReversalThreshold: BigDecimal?,
    val sellRatio: BigDecimal,
    val sellTiming: String,
    val delaySellSeconds: Int,
    val priceStrategy: String,
    val fixedPrice: BigDecimal?,
    val priceOffset: BigDecimal,
    val maxPosition: BigDecimal,
    val minPosition: BigDecimal,
    val maxGamePosition: BigDecimal?,
    val maxDailyLoss: BigDecimal?,
    val maxDailyOrders: Int?,
    val maxDailyProfit: BigDecimal?,
    val priceTolerance: BigDecimal,
    val minProbabilityThreshold: BigDecimal?,
    val maxProbabilityThreshold: BigDecimal?,
    val baseStrengthWeight: BigDecimal,
    val recentFormWeight: BigDecimal,
    val lineupIntegrityWeight: BigDecimal,
    val starStatusWeight: BigDecimal,
    val environmentWeight: BigDecimal,
    val matchupAdvantageWeight: BigDecimal,
    val scoreDiffWeight: BigDecimal,
    val momentumWeight: BigDecimal,
    val dataUpdateFrequency: Int,
    val analysisFrequency: Int,
    val pushFailedOrders: Boolean,
    val pushFrequency: String,
    val batchPushInterval: Int,
    val createdAt: Long,
    val updatedAt: Long
)

/**
 * NBA 量化策略创建请求
 */
data class NbaQuantitativeStrategyCreateRequest(
    val strategyName: String,
    val strategyDescription: String? = null,
    val accountId: Long,
    val enabled: Boolean = true,
    val filterTeams: List<String>? = null,
    val filterDateFrom: LocalDate? = null,
    val filterDateTo: LocalDate? = null,
    val filterGameImportance: String? = null,
    val minWinProbabilityDiff: BigDecimal? = null,
    val minWinProbability: BigDecimal? = null,
    val maxWinProbability: BigDecimal? = null,
    val minTradeValue: BigDecimal? = null,
    val minRemainingTime: Int? = null,
    val maxRemainingTime: Int? = null,
    val minScoreDiff: Int? = null,
    val maxScoreDiff: Int? = null,
    val buyAmountStrategy: String? = null,
    val fixedBuyAmount: BigDecimal? = null,
    val buyRatio: BigDecimal? = null,
    val baseBuyAmount: BigDecimal? = null,
    val buyTiming: String? = null,
    val delayBuySeconds: Int? = null,
    val buyDirection: String? = null,
    val enableSell: Boolean? = null,
    val takeProfitThreshold: BigDecimal? = null,
    val stopLossThreshold: BigDecimal? = null,
    val probabilityReversalThreshold: BigDecimal? = null,
    val sellRatio: BigDecimal? = null,
    val sellTiming: String? = null,
    val delaySellSeconds: Int? = null,
    val priceStrategy: String? = null,
    val fixedPrice: BigDecimal? = null,
    val priceOffset: BigDecimal? = null,
    val maxPosition: BigDecimal? = null,
    val minPosition: BigDecimal? = null,
    val maxGamePosition: BigDecimal? = null,
    val maxDailyLoss: BigDecimal? = null,
    val maxDailyOrders: Int? = null,
    val maxDailyProfit: BigDecimal? = null,
    val priceTolerance: BigDecimal? = null,
    val minProbabilityThreshold: BigDecimal? = null,
    val maxProbabilityThreshold: BigDecimal? = null,
    val baseStrengthWeight: BigDecimal? = null,
    val recentFormWeight: BigDecimal? = null,
    val lineupIntegrityWeight: BigDecimal? = null,
    val starStatusWeight: BigDecimal? = null,
    val environmentWeight: BigDecimal? = null,
    val matchupAdvantageWeight: BigDecimal? = null,
    val scoreDiffWeight: BigDecimal? = null,
    val momentumWeight: BigDecimal? = null,
    val dataUpdateFrequency: Int? = null,
    val analysisFrequency: Int? = null,
    val pushFailedOrders: Boolean? = null,
    val pushFrequency: String? = null,
    val batchPushInterval: Int? = null
)

/**
 * NBA 量化策略更新请求
 */
data class NbaQuantitativeStrategyUpdateRequest(
    val id: Long,
    val strategyName: String? = null,
    val strategyDescription: String? = null,
    val enabled: Boolean? = null,
    val filterTeams: List<String>? = null,
    val filterDateFrom: LocalDate? = null,
    val filterDateTo: LocalDate? = null,
    val filterGameImportance: String? = null,
    val minWinProbabilityDiff: BigDecimal? = null,
    val minWinProbability: BigDecimal? = null,
    val maxWinProbability: BigDecimal? = null,
    val minTradeValue: BigDecimal? = null,
    val minRemainingTime: Int? = null,
    val maxRemainingTime: Int? = null,
    val minScoreDiff: Int? = null,
    val maxScoreDiff: Int? = null,
    val buyAmountStrategy: String? = null,
    val fixedBuyAmount: BigDecimal? = null,
    val buyRatio: BigDecimal? = null,
    val baseBuyAmount: BigDecimal? = null,
    val buyTiming: String? = null,
    val delayBuySeconds: Int? = null,
    val buyDirection: String? = null,
    val enableSell: Boolean? = null,
    val takeProfitThreshold: BigDecimal? = null,
    val stopLossThreshold: BigDecimal? = null,
    val probabilityReversalThreshold: BigDecimal? = null,
    val sellRatio: BigDecimal? = null,
    val sellTiming: String? = null,
    val delaySellSeconds: Int? = null,
    val priceStrategy: String? = null,
    val fixedPrice: BigDecimal? = null,
    val priceOffset: BigDecimal? = null,
    val maxPosition: BigDecimal? = null,
    val minPosition: BigDecimal? = null,
    val maxGamePosition: BigDecimal? = null,
    val maxDailyLoss: BigDecimal? = null,
    val maxDailyOrders: Int? = null,
    val maxDailyProfit: BigDecimal? = null,
    val priceTolerance: BigDecimal? = null,
    val minProbabilityThreshold: BigDecimal? = null,
    val maxProbabilityThreshold: BigDecimal? = null,
    val baseStrengthWeight: BigDecimal? = null,
    val recentFormWeight: BigDecimal? = null,
    val lineupIntegrityWeight: BigDecimal? = null,
    val starStatusWeight: BigDecimal? = null,
    val environmentWeight: BigDecimal? = null,
    val matchupAdvantageWeight: BigDecimal? = null,
    val scoreDiffWeight: BigDecimal? = null,
    val momentumWeight: BigDecimal? = null,
    val dataUpdateFrequency: Int? = null,
    val analysisFrequency: Int? = null,
    val pushFailedOrders: Boolean? = null,
    val pushFrequency: String? = null,
    val batchPushInterval: Int? = null
)

/**
 * NBA 量化策略列表请求
 */
data class NbaQuantitativeStrategyListRequest(
    val accountId: Long? = null,
    val enabled: Boolean? = null,
    val strategyName: String? = null,
    val page: Int? = 1,
    val limit: Int? = 20
)

/**
 * NBA 量化策略列表响应
 */
data class NbaQuantitativeStrategyListResponse(
    val list: List<NbaQuantitativeStrategyDto>,
    val total: Long,
    val page: Int,
    val limit: Int
)

