#!/usr/bin/env python3
"""
PolyHermes AI Fixer
Automated AI-powered bug fixer for PolyHermes project

This script implements the complete workflow:
1. Fetch GitHub Issues with 'fix via ai' label
2. Create ai_fix/n_xxx branches for each issue
3. Apply AI fixes using Cursor Agent
4. Verify frontend and backend compilation
5. Commit and push changes
6. Create PRs and comment on issues
"""

import os
import sys
import subprocess
import json
import re
import time
from typing import List, Dict, Optional
from datetime import datetime

class PolyHermesAIFixer:
    def __init__(self):
        self.repo_root = os.getcwd()
        self.issues = []
        self.fixed_issues = []
        
    def log(self, message: str, level: str = "INFO"):
        """Log messages with timestamp"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{timestamp}] {level}: {message}")
    
    def run_command(self, command: str, cwd: str = None, check: bool = True) -> Optional[str]:
        """Run shell command and return output"""
        self.log(f"Running: {command}")
        try:
            result = subprocess.run(
                command, 
                shell=True, 
                capture_output=True, 
                text=True, 
                cwd=cwd or self.repo_root,
                check=check
            )
            if result.stdout:
                self.log(f"Output: {result.stdout.strip()}")
            return result.stdout
        except subprocess.CalledProcessError as e:
            self.log(f"Command failed: {e}", "ERROR")
            self.log(f"Error output: {e.stderr}", "ERROR")
            if check:
                raise
            return None
    
    def fetch_issues(self) -> List[Dict]:
        """Fetch GitHub Issues with 'fix via ai' label"""
        self.log("Fetching GitHub Issues with 'fix via ai' label...")
        
        try:
            # Get repository information
            remote_url = self.run_command("git remote get-url origin")
            if not remote_url:
                self.log("Failed to get remote repository URL", "ERROR")
                return []
            
            # Extract owner/repo from remote URL
            match = re.search(r"github\.com[:/](.+?)/(.+?)(\.git)?$", remote_url)
            if not match:
                self.log("Failed to parse repository URL", "ERROR")
                return []
            
            owner, repo = match.groups()[:2]
            self.log(f"Repository: {owner}/{repo}")
            
            # Search issues with 'fix via ai' label
            command = f"gh issue list --label 'fix via ai' --json number,title,body,state"
            output = self.run_command(command)
            
            if not output:
                self.log("No issues found with 'fix via ai' label")
                return []
            
            # Parse JSON output
            issues = json.loads(output)
            self.log(f"Found {len(issues)} issues requiring AI fixes")
            
            for issue in issues:
                self.log(f"Issue #{issue['number']}: {issue['title']}")
            
            return issues
            
        except Exception as e:
            self.log(f"Error fetching issues: {e}", "ERROR")
            return []
    
    def create_fix_branch(self, issue_number: int) -> bool:
        """Create ai_fix/n_xxx branch for the issue"""
        branch_name = f"ai_fix/n_{issue_number}"
        
        try:
            # Switch to main branch
            self.run_command("git checkout main")
            
            # Pull latest changes
            self.run_command("git pull origin main")
            
            # Create new branch
            self.run_command(f"git checkout -b {branch_name}")
            
            self.log(f"Created branch: {branch_name}")
            return True
            
        except Exception as e:
            self.log(f"Failed to create branch {branch_name}: {e}", "ERROR")
            return False
    
    def apply_ai_fix(self, issue_number: int, issue_title: str) -> bool:
        """Apply AI fix using Cursor Agent"""
        self.log(f"Applying AI fix for issue #{issue_number}: {issue_title}")
        
        try:
            # Here we would call Cursor Agent to apply the fix
            # For now, we'll create a placeholder fix file
            fix_content = f"""# Issue #{issue_number} Fix
# Title: {issue_title}

# This is a placeholder AI-generated fix
# In a real implementation, this would be generated by Cursor Agent

def fix_issue_{issue_number}():
    \"\"\"
    AI-generated fix for issue #{issue_number}
    {issue_title}
    \"\"\"
    # TODO: Implement actual fix based on issue description
    pass

print("AI fix applied for issue #{issue_number}")
"""

            fix_file = f"ai_fix_issue_{issue_number}.py"
            with open(fix_file, 'w') as f:
                f.write(fix_content)
            
            self.log(f"Created fix file: {fix_file}")
            return True
            
        except Exception as e:
            self.log(f"Failed to apply AI fix: {e}", "ERROR")
            return False
    
    def verify_builds(self) -> bool:
        """Verify frontend and backend compilation"""
        self.log("Verifying builds...")
        
        try:
            # Verify frontend build
            self.log("Checking frontend...")
            frontend_result = self.run_command("cd frontend && npm run build", check=False)
            if frontend_result is None:
                self.log("Frontend build failed", "ERROR")
                return False
            
            # Verify backend build
            self.log("Checking backend...")
            backend_result = self.run_command("cd backend && ./gradlew build", check=False)
            if backend_result is None:
                self.log("Backend build failed", "ERROR")
                return False
            
            self.log("Build verification passed")
            return True
            
        except Exception as e:
            self.log(f"Build verification failed: {e}", "ERROR")
            return False
    
    def commit_and_push(self, issue_number: int) -> bool:
        """Commit changes and push to remote"""
        self.log("Committing and pushing changes...")
        
        try:
            # Add files
            self.run_command("git add .")
            
            # Commit
            commit_message = f"AI fix for issue #{issue_number}"
            self.run_command(f"git commit -m \"{commit_message}\"")
            
            # Push
            branch_name = f"ai_fix/n_{issue_number}"
            self.run_command(f"git push origin {branch_name}")
            
            self.log(f"Successfully pushed branch: {branch_name}")
            return True
            
        except Exception as e:
            self.log(f"Failed to commit and push: {e}", "ERROR")
            return False
    
    def create_pr(self, issue_number: int, issue_title: str) -> bool:
        """Create pull request for the fix"""
        self.log(f"Creating PR for issue #{issue_number}...")
        
        try:
            branch_name = f"ai_fix/n_{issue_number}"
            
            # Create PR
            pr_title = f"AI fix for #{issue_number}: {issue_title}"
            pr_body = f"""
This PR contains an AI-generated fix for issue #{issue_number}.

**Issue Title**: {issue_title}
**Branch**: {branch_name}
**Fix Type**: AI-generated

The fix was automatically generated using the PolyHermes AI Fixer tool.

Please review the changes carefully before merging.

Closes #{issue_number}
"""
            
            command = f"gh pr create --title \"{pr_title}\" --body \"{pr_body}\" --base main --head {branch_name}"
            output = self.run_command(command)
            
            if output:
                pr_url = output.strip()
                self.log(f"Created PR: {pr_url}")
                
                # Comment on issue
                comment = f"AI fix has been created in PR: {pr_url}"
                self.run_command(f"gh issue comment {issue_number} --body \"{comment}\"")
                
                return True
            else:
                self.log("Failed to create PR", "ERROR")
                return False
                
        except Exception as e:
            self.log(f"Failed to create PR: {e}", "ERROR")
            return False
    
    def process_issue(self, issue: Dict) -> bool:
        """Process a single issue through the complete workflow"""
        issue_number = issue['number']
        issue_title = issue['title']
        
        self.log(f"Processing issue #{issue_number}: {issue_title}")
        
        try:
            # Step 1: Create fix branch
            if not self.create_fix_branch(issue_number):
                return False
            
            # Step 2: Apply AI fix
            if not self.apply_ai_fix(issue_number, issue_title):
                return False
            
            # Step 3: Verify builds
            if not self.verify_builds():
                return False
            
            # Step 4: Commit and push
            if not self.commit_and_push(issue_number):
                return False
            
            # Step 5: Create PR
            if not self.create_pr(issue_number, issue_title):
                return False
            
            self.log(f"Successfully processed issue #{issue_number}")
            self.fixed_issues.append(issue_number)
            return True
            
        except Exception as e:
            self.log(f"Failed to process issue #{issue_number}: {e}", "ERROR")
            return False
    
    def run(self):
        """Execute the complete AI fixing workflow"""
        self.log("Starting PolyHermes AI Fixer workflow...")
        
        # Step 1: Fetch issues
        self.issues = self.fetch_issues()
        if not self.issues:
            self.log("No issues found requiring AI fixes")
            return
        
        # Step 2: Process each issue
        success_count = 0
        for issue in self.issues:
            if self.process_issue(issue):
                success_count += 1
            else:
                self.log(f"Skipping issue #{issue['number']} due to errors", "WARNING")
            
            # Small delay between issues to avoid rate limiting
            time.sleep(1)
        
        # Summary
        self.log(f"Workflow completed. Successfully processed {success_count}/{len(self.issues)} issues")
        
        if self.fixed_issues:
            self.log(f"Fixed issues: {', '.join(map(str, self.fixed_issues))}")

def main():
    """Main entry point"""
    try:
        fixer = PolyHermesAIFixer()
        fixer.run()
        return 0
    except Exception as e:
        print(f"Fatal error: {e}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())